### ISSUE TITLE
fix buttons not givin you anything

### ISSUE THREAD

**Issue by Artistic-Waffle** [universalcrew/FormShop#2]

**Comment by nikipuh** [comment]
it should repair your item i think

**Comment by Artistic-Waffle** [comment]
huh

**Comment by Artistic-Waffle** [comment]
add more shops and fix buttons and window on giving player there stuff when use of forms

**Comment by egr7v8** [comment]
Update the config:

- "262:0:4"

**Comment by Artistic-Waffle** [comment]
like how could you show me a pic in english pls
